"""Shared import logic for the seed normativa format (HLD §7), used by both
`POST /admin/normativa/import` and `python -m app.seed`.

Format::

    {
      "cuerpos": [{"code","nombre","tipo","numero","fecha","fuente_url"}],
      "articulos": [{"cuerpo","numero","inciso","titulo","texto","fuente_url","verificado"}]
    }

`articulos[].cuerpo` references `cuerpos[].code` (or an already-existing
`cuerpos_legales.code`). The importer resolves cuerpo_id and upserts by
(cuerpo_id, numero, inciso) keeping the row at version 1 on update (no
history is generated by import).
"""

from datetime import date

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Articulo, CuerpoLegal


def _parse_date(value: str | None) -> date | None:
    if not value:
        return None
    try:
        return date.fromisoformat(value)
    except ValueError:
        return None


async def import_normativa(db: AsyncSession, data: dict) -> dict:
    cuerpos_creados = cuerpos_actualizados = 0
    articulos_creados = articulos_actualizados = 0

    cuerpo_by_code: dict[str, CuerpoLegal] = {}

    for c in data.get("cuerpos", []):
        code = c["code"]
        result = await db.execute(select(CuerpoLegal).where(CuerpoLegal.code == code))
        row = result.scalars().first()
        if row is None:
            row = CuerpoLegal(
                code=code,
                nombre=c.get("nombre", code),
                tipo=c.get("tipo", ""),
                numero=c.get("numero"),
                fecha=_parse_date(c.get("fecha")),
                fuente_url=c.get("fuente_url", ""),
            )
            db.add(row)
            cuerpos_creados += 1
        else:
            row.nombre = c.get("nombre", row.nombre)
            row.tipo = c.get("tipo", row.tipo)
            row.numero = c.get("numero", row.numero)
            row.fecha = _parse_date(c.get("fecha")) or row.fecha
            row.fuente_url = c.get("fuente_url", row.fuente_url)
            cuerpos_actualizados += 1
        cuerpo_by_code[code] = row

    await db.flush()

    # Resolve any cuerpo codes referenced by articulos but not present in this
    # import's `cuerpos` list against already-existing rows in the DB.
    missing_codes = {a["cuerpo"] for a in data.get("articulos", [])} - set(cuerpo_by_code)
    if missing_codes:
        result = await db.execute(select(CuerpoLegal).where(CuerpoLegal.code.in_(missing_codes)))
        for row in result.scalars().all():
            cuerpo_by_code[row.code] = row

    for a in data.get("articulos", []):
        cuerpo = cuerpo_by_code.get(a["cuerpo"])
        if cuerpo is None:
            raise ValueError(f"cuerpo legal desconocido: {a['cuerpo']}")

        numero = a["numero"]
        inciso = a.get("inciso")
        result = await db.execute(
            select(Articulo).where(
                Articulo.cuerpo_id == cuerpo.id,
                Articulo.numero == numero,
                Articulo.inciso == inciso,
            )
        )
        row = result.scalars().first()
        if row is None:
            row = Articulo(
                cuerpo_id=cuerpo.id,
                numero=numero,
                inciso=inciso,
                titulo=a.get("titulo"),
                texto=a["texto"],
                fuente_url=a.get("fuente_url", ""),
                verificado=a.get("verificado", False),
                vigente=True,
                version=1,
            )
            db.add(row)
            articulos_creados += 1
        else:
            row.titulo = a.get("titulo", row.titulo)
            row.texto = a.get("texto", row.texto)
            row.fuente_url = a.get("fuente_url", row.fuente_url)
            row.verificado = a.get("verificado", row.verificado)
            articulos_actualizados += 1

    await db.commit()

    return {
        "cuerpos_creados": cuerpos_creados,
        "cuerpos_actualizados": cuerpos_actualizados,
        "articulos_creados": articulos_creados,
        "articulos_actualizados": articulos_actualizados,
    }
